### ISSUE TITLE
It's not set up there??

### ISSUE THREAD

**Issue by 392377870** [SaraSmiseth/dynv6-updater#3]
Started.

ip: can't find device ''

run-parts: /etc/periodic/1min/dynv6: exit status 1

**Comment by SaraSmiseth** [comment]
Are you using host network mode and have you changed the interface name (DYNV6_NETWORK_DEVICE)? Maybe the interface name is wrong? Your error message suggests, that it can not find the interface. I can replicate that behavior if I use random text for the interface name.

You can get the correct name with `ip a`.

I'm sorry that the readme is not up to date. I'll fix that later.

**Comment by 392377870** [comment]
还有那里设置的不对？？这个我也是刚刚接触不久，

**Comment by 392377870** [comment]
还有那里设置的不对？？这个我也是刚刚接触不久，


What's wrong with the settings there?? I have just come into contact with this.

**Comment by SaraSmiseth** [comment]
I suggest you use the example [docker-compose.yml](https://github.com/SaraSmiseth/dynv6-updater/blob/dev/docker-compose.yml).
Edit the example and change `DYNV6_TOKEN=change this to your token`, `DYNV6_ZONES=change this to your zone` and `DYNV6_NETWORK_DEVICE=change this to your interface`.
