### ISSUE TITLE
Error reported when two ipv6 addresses are owned at the same time

### ISSUE THREAD

**Issue by fatinghenji** [SaraSmiseth/dynv6-updater#4]
When I use `ip a`, I find that I have two ipv6 addresses in `wlan1` at the same time.
Then when I start the program the console reports the following error.
```
wget: server returned error: HTTP/1.1 400 Bad Request
run-parts: /etc/periodic/1min/dynv6: exit status 1
```
I think the reason is that it submits two ipv6 addresses at the same time in the message, which looks like this
```
2022-10-07 15:34:00: Calling: wget -qO- https://dynv6.com/api/update?hostname=myzone.dynv6.net&token=mytoken& ipv6=ipv6adress1
ipv6adress2
```
As shown above, two ipv6 addresses are being handed over at the same time, how should I solve this problem?
![image](https://user-images.githubusercontent.com/37131177/194593455-be03ab62-c1fd-471a-9d67-98d5fd5e6f3c.png)

**Comment by SaraSmiseth** [comment]
You can use the environment variable `DYNV6_IP_ADDRESS_FILTER`to filter the result of `ip a`.

The variable is used with grep like this:

``` bash
ip a | grep "$DYNV6_IP_ADDRESS_FILTER"
```

You can set it to `4de1`for example if you want the first one. This only works if this part does not change. I use it like this and I have my ipv6 configured to be generated by the interfaces mac address.

I changed `slaac private` to `slaac hwaddr` in `/etc/dhcpcd.conf`.
